### ISSUE TITLE
KeyError: 'ATag' - Deepparse 0.9.9

### ISSUE THREAD

**Issue by ArbazMubasher** [GRAAL-Research/deepparse#209]
Hello. My deepparse version is 0.9.9 and I am currently trying to retrain a model using custom prediction tags. The code is as follows:

```
import os

import poutyne

#from deepparse import download_from_public_repository
from deepparse.dataset_container import PickleDatasetContainer
from deepparse.parser import AddressParser

# First, let's download the train and test data with the new tags, "new tags", from the public repository.
saving_dir = "./data"
file_extension = "p"
training_dataset_name = "sample_incomplete_data_new_prediction_tags"
test_dataset_name = "test_sample_data_new_prediction_tags"
#download_from_public_repository(training_dataset_name, saving_dir, file_extension=file_extension)
#download_from_public_repository(test_dataset_name, saving_dir, file_extension=file_extension)

# Now let's create a training and test container.
training_container = PickleDatasetContainer(os.path.join(saving_dir, training_dataset_name + "." + file_extension))
test_container = PickleDatasetContainer(os.path.join(saving_dir, test_dataset_name + "." + file_extension))

# We will retrain the FastText version of our pretrained model.
model = "bpemb"
address_parser = AddressParser(model_type=model, device=0)

# Now, let's retrain for 5 epochs using a batch size of 8 since the data is really small for the example.
# Let's start with the default learning rate of 0.01 and use a learning rate scheduler to lower the learning rate
# as we progress.
lr_scheduler = poutyne.StepLR(step_size=1, gamma=0.1)  # reduce LR by a factor of 10 each epoch

# We need a EOS tag in the dictionary. EOS -> End Of Sequence
tag_dictionary = {"Street": 0, "Locality": 1, "Subarea": 2,"Area": 3,"Town/Village": 4, "City": 5,"City": 6,"City": 7,"City": 8,"EOS": 9}

# The path to save our checkpoints
logging_path = "./checkpoints"

address_parser.retrain(
    training_container,
    train_ratio=0.8,
    epochs=5,
    batch_size=8,
    num_workers=2,
    callbacks=[lr_scheduler],
    prediction_tags=tag_dictionary,
    logging_path=logging_path,
)

# Now, let's test our fine-tuned model using the best checkpoint (default parameter).
address_parser.test(test_container, batch_size=256)

# One can also freeze the seq2seq layer to only retrain the prediction layer using the new tag prediction space.
# That way, training will be faster.
address_parser.retrain(
    training_container,
    train_ratio=0.8,
    epochs=5,
    batch_size=8,
    num_workers=2,
    callbacks=[lr_scheduler],
    prediction_tags=tag_dictionary,
    logging_path=logging_path,
    layers_to_freeze="seq2seq",
)

# Now let's see how we can reload our new AddressParser.
# When you retrain a model, at the end, we create a retrained checkpoint using the best checkpoint
# and also include some metadata for the reloading (the tags, the dimension, etc.).
# By defaults, the checkpoint is named "retrain_modeltype_parser.ckpt".
retrain_model_path = os.path.join("checkpoints", "retrained_bpemb_address_parser.ckpt")
address_parser = AddressParser(path_to_retrained_model=retrain_model_path)
```

The error I am getting is as follows:

```
2023-08-24 17:46:05.699533: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-24 17:46:06.214339: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading the embeddings model
Traceback (most recent call last):
  File "/home/arbaz/deepparse/examples/retrain_with_new_prediction_tags.py", line 36, in <module>
    address_parser.retrain(
  File "/home/arbaz/.local/lib/python3.10/site-packages/deepparse/parser/address_parser.py", line 799, in retrain
    train_res = self._retrain(
  File "/home/arbaz/.local/lib/python3.10/site-packages/deepparse/parser/address_parser.py", line 1202, in _retrain
    train_res = experiment.train(
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/model_bundle.py", line 751, in train
    return self._train(self.model.fit_generator, train_generator, valid_generator, **kwargs)
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/model_bundle.py", line 912, in _train
    return training_func(*args, initial_epoch=initial_epoch, callbacks=expt_callbacks, **kwargs)
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/model.py", line 610, in fit_generator
    self._fit_generator_one_batch_per_step(epoch_iterator, callback_list)
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/model.py", line 680, in _fit_generator_one_batch_per_step
    for step, (x, y) in train_step_iterator:
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/iterators.py", line 89, in __iter__
    for step, data in _get_step_iterator(self.steps_per_epoch, self.generator):
  File "/home/arbaz/.local/lib/python3.10/site-packages/poutyne/framework/iterators.py", line 35, in cycle
    for x in iterable:
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/arbaz/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/arbaz/.local/lib/python3.10/site-packages/deepparse/converter/data_processor.py", line 82, in process_for_training
    target_tmp = [self.tags_converter(target) for target in target_list]
  File "/home/arbaz/.local/lib/python3.10/site-packages/deepparse/converter/data_processor.py", line 82, in <listcomp>
    target_tmp = [self.tags_converter(target) for target in target_list]
  File "/home/arbaz/.local/lib/python3.10/site-packages/deepparse/converter/target_converter.py", line 22, in __call__
    return self.tags_to_idx[key]
KeyError: 'ATag'
```

I have tried changing logging paths and changed versions of the deepparse as well. The change in version to 0.5.5 results in RuntimeError: Error(s) in loading state_dict for BPEmbSeq2SeqModel

**Comment by davebulaval** [comment]
The problem is the mismatch between the dataset tag and those you want to use, i.e. `tag_dictionary = {"Street": 0, "Locality": 1, "Subarea": 2,"Area": 3,"Town/Village": 4, "City": 5,"City": 6,"City": 7,"City": 8,"EOS": 9}`.

The dataset you are trying to use is a fake one with fake tags such as `"ATag."`. This does not fit in the tag names you want to parse with. 

To work, you need to provide a small tagged dataset with the tag you want to use to train the model with new tags.

**Comment by ArbazMubasher** [comment]
@davebulaval I have been trying to follow the tutorials and examples in the repo to do exactly that. Would you be able to share the steps necessary to train a tokenized CSV of addresses?

Much regards

**Comment by davebulaval** [comment]
@ArbazMubasher I have just tested locally this script to retrain with new tags with a new clean install with Deepparse version 0.9.9, and everything works fine.

https://github.com/GRAAL-Research/deepparse/blob/main/examples/retrain_with_new_prediction_tags.py

### If your question is: "How can I get a training dataset with the tags I want?"
You need to either manually or semi-manually annotate the address with the desired tags. By that, I mean having something like: "An address", ["New tag", "streetName"] or whatever tag you want.

@MAYAS3  is currently working on tips and tricks on that matter. 

The easiest way to do it is to manually annotate a few addresses (50 or so), and train our pre-trained model. Use this fine-tuned model and parse 50 or so addresses. 
Manually validate that the tags are properly parsed. Now you have 100 or so annotated addresses and the second batch was easier to make than the first 50 or so.
Train again our pre-trained model with the 100 or so addresses. Parse another batch of addresses and manually validate that the tags are properly parsed. 
And rinse and repeat until performance is as expected. This method is called bootstrapping. Unfortunately, there is no quicker way other than that.
